
CREATE TABLE USER_DETAILS 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BIRTH_DATE" DATE, 
	"NAME" VARCHAR2(255), 
	PRIMARY KEY ("ID")
  );

CREATE TABLE USER_POSTS 
   (	
    "ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"USER_ID" NUMBER(20,0), 
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "POST_FK1"
	  FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_DETAILS" ("ID")
   );
   
    CREATE TABLE LOGIN_USERS 
   (	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("USERNAME")
   );
   
     CREATE TABLE AUTHORITIES 
   (	"USERNAME" VARCHAR2(50), 
		"AUTHORITY" VARCHAR2(20), 
	 	CONSTRAINT "AUTHORITIES_FK1" 
	 	FOREIGN KEY ("USERNAME")
	  	REFERENCES "LOGIN_USERS" ("USERNAME")
   );


Insert into LOGIN_USERS (USERNAME,PASSWORD,ENABLED) values ('admin','$2a$10$hbxecwitQQ.dDT4JOFzQAulNySFwEpaFLw38jda6Td.Y/cOiRzDFu',1);
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('admin','ROLE_ADMIN');



commit;