
CREATE TABLE USER_DETAILS 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BIRTH_DATE" DATE, 
	"NAME" VARCHAR2(255), 
	PRIMARY KEY ("ID")
  );

CREATE TABLE USER_POSTS 
   (	
    "ID" NUMBER(20,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"USER_ID" NUMBER(20,0), 
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "POST_FK1"
	  FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_DETAILS" ("ID")
   );
   
    CREATE TABLE LOGIN_USERS 
   (	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("USERNAME")
   );
   
     CREATE TABLE AUTHORITIES 
   (	"USERNAME" VARCHAR2(50), 
		"AUTHORITY" VARCHAR2(20), 
	 	CONSTRAINT "AUTHORITIES_FK1" 
	 	FOREIGN KEY ("USERNAME")
	  	REFERENCES "LOGIN_USERS" ("USERNAME")
   );


Insert into LOGIN_USERS (USERNAME,PASSWORD,ENABLED) values ('admin','$2a$10$hbxecwitQQ.dDT4JOFzQAulNySFwEpaFLw38jda6Td.Y/cOiRzDFu',1);
Insert into AUTHORITIES (USERNAME,AUTHORITY) values ('admin','ROLE_ADMIN');


INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES ('1', TO_DATE('1950-11-17 08:39:15', 'YYYY-MM-DD HH24:MI:SS'), 'Testing Name1');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE) VALUES ('2', TO_DATE('1970-11-13 08:39:49', 'YYYY-MM-DD HH24:MI:SS', "Testing Name 2"));

INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('10', 'Shopped in Romania', '1');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('11', '5 Atm with drawals in 3 hours', '1');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('12', 'Shopped within credit Limit thrice in Last 3 months ', '1');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('13', 'Shopped at Suspicious Mcc Terminal', '1');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('14', 'Failed login Pin attempts', '2');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('15', 'Reported disputed transactions', '2');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('16', 'Used Overdraft many times', '2');
INSERT INTO USER_POSTS (ID, DESCRIPTION, USER_ID) VALUES ('17', 'Has Police warnings about inpersonation of accont', '2');









commit;